import 'server-only';

import { getClientById as dbGetClientById } from '@/lib/db/clients';
import { getProvenanceMeta } from '@/lib/operator-intelligence/provenance';
import { loadIndependentSources, getSourceStatus } from '@/lib/operator-intelligence/source-availability';
import { getClientConnectorRows } from '@/lib/connectors/repository';
import {
    getLatestCollectionRun,
    listClusters,
    listOpportunities,
    getCommunityStats,
} from '@/lib/db/community';
import { evidenceLevel } from '@/lib/agent-reach/contracts';
import { resolveBusinessType } from '@/lib/ai/business-type-resolver';

// ──────────────────────────────────────────────────────────────
// Helpers — resolve richer site context for the social view
// ──────────────────────────────────────────────────────────────

function buildSiteContext(client) {
    const clientName = String(client?.client_name || '').trim();
    const rawBusinessType = String(client?.business_type || '').trim();
    const city = String(client?.address?.city || client?.target_region || '').trim();

    const siteClassification = client?.site_classification || {};
    const resolved = resolveBusinessType(rawBusinessType, siteClassification, clientName);

    // Pick the best human-readable label: offering_anchor > resolved category > raw type
    const businessLabel = resolved.offering_anchor
        || (resolved.canonical_category !== 'unknown' ? resolved.canonical_category.replace(/_/g, ' ') : '')
        || rawBusinessType
        || null;

    return {
        client_name: clientName || null,
        business_type: businessLabel,
        city: city || null,
        canonical_category: resolved.canonical_category || null,
        business_model: resolved.business_model_detected || null,
        target_audience: resolved.target_audience || null,
        category_confidence: resolved.category_confidence || null,
    };
}

// ──────────────────────────────────────────────────────────────
// Helpers — format persisted clusters/opportunities for UI
// ──────────────────────────────────────────────────────────────

function formatClusterItems(clusters, clusterType, { maxItems = 10 } = {}) {
    return clusters
        .filter((c) => c.cluster_type === clusterType)
        .slice(0, maxItems)
        .map((c) => ({
            label: c.label,
            count: c.mention_count,
            evidence_level: c.evidence_level || evidenceLevel(c.mention_count),
            subreddits: (c.sources || []).slice(0, 4),
            example: c.example_url || null,
        }));
}

function formatSourceBuckets(clusters) {
    return clusters
        .filter((c) => c.cluster_type === 'source_bucket')
        .slice(0, 10)
        .map((c) => ({
            source: c.label,
            count: c.mention_count,
            evidence_level: c.evidence_level || evidenceLevel(c.mention_count),
        }));
}

function formatOpportunities(opportunities, type, { maxItems = 8 } = {}) {
    return opportunities
        .filter((o) => o.opportunity_type === type)
        .slice(0, maxItems)
        .map((o) => ({
            title: o.title,
            rationale: o.rationale,
            evidence_level: o.evidence_level,
            mention_count: o.mention_count,
            provenance: getProvenanceMeta(o.provenance || 'inferred'),
            // v2 metadata (available when generated by v2 pipeline)
            why_it_matters: o.metadata?.why_it_matters || null,
            suggested_action: o.metadata?.suggested_action || null,
            source_url: o.metadata?.source_url || null,
            signal_family: o.metadata?.signal_family || null,
            composite_score: o.metadata?.composite_score ?? null,
        }));
}

function resolveConnectionStatus(connectorRow, latestRun, stats, dataSources) {
    if (dataSources.connectorRows === 'unavailable') {
        return {
            status: 'unavailable',
            connector: 'agent_reach',
            message: 'État du connecteur temporairement indisponible.',
        };
    }
    if (!connectorRow || connectorRow.status === 'not_connected') {
        return {
            status: 'not_connected',
            connector: 'agent_reach',
            message:
                latestRun || dataSources.latestRun === 'unavailable' || stats?.documents > 0
                    ? 'Intelligence communautaire non connectée actuellement.'
                    : 'Intelligence communautaire non connectée, aucune collecte externe n\'a été exécutée.',
            requirement: 'Lancez une collecte manuelle ou attendez le prochain cycle du moteur continu.',
        };
    }

    if (connectorRow.status === 'error' || latestRun?.status === 'failed') {
        return {
            status: 'error',
            connector: 'agent_reach',
            message: 'La dernière collecte a échoué.',
            detail: latestRun?.error_message || connectorRow.health_detail || null,
        };
    }

    if (connectorRow.status === 'syncing' || latestRun?.status === 'running') {
        return {
            status: 'syncing',
            connector: 'agent_reach',
            message: 'Collecte en cours…',
        };
    }

    if (stats?.documents == null) {
        return {
            status: 'unavailable',
            connector: 'agent_reach',
            message: 'Données communautaires temporairement indisponibles.',
        };
    }

    if (stats.documents === 0) {
        return {
            status: 'connected_empty',
            connector: 'agent_reach',
            message: 'Connecteur actif mais aucune donnée collectée pour le moment.',
            caveat: 'La première collecte sera déclenchée par le moteur continu selon le cadence configurée.',
        };
    }

    return {
        status: 'connected',
        connector: 'agent_reach',
        message: 'Observé en externe à partir de données communautaires collectées et persistées.',
        caveat: 'La couverture est limitée aux seeds suivis et ne constitue pas une veille sociale universelle.',
    };
}

// ──────────────────────────────────────────────────────────────
// Not-connected empty slice (preserves shape)
// ──────────────────────────────────────────────────────────────

function buildNotConnectedSlice(client, availability) {
    const siteContext = buildSiteContext(client);
    return {
        ...availability,
        provenance: {
            observation: getProvenanceMeta('observed'),
            inferred: getProvenanceMeta('inferred'),
            not_connected: getProvenanceMeta('not_connected'),
        },
        connection: {
            status: 'not_connected',
            connector: 'agent_reach',
            message: 'Intelligence communautaire non connectée, aucune collecte externe n\'a été exécutée.',
            requirement: 'Lancez une collecte manuelle ou attendez le prochain cycle du moteur continu.',
        },
        summary: {
            generated_at: new Date().toISOString(),
            total_discussions: 0,
            unique_sources: 0,
            documents_count: 0,
            clusters_count: 0,
            opportunities_count: 0,
            mentions_count: 0,
            site_context: siteContext,
            query_seeds: [],
            last_run: null,
        },
        topComplaints: [],
        topQuestions: [],
        topThemes: [],
        sourceBuckets: [],
        competitorComplaints: [],
        communityLanguage: [],
        faqOpportunities: [],
        contentOpportunities: [],
        differentiationAngles: [],
        buyerQuestions: [],
        comparisonDiscussions: [],
        painPoints: [],
        responseOpportunities: [],
        aiMentionOpportunities: [],
        contentAngleOpportunities: [],
        emptyState: {
            title: 'Intelligence communautaire non connectée',
            description: 'Aucune collecte n\'a encore eu lieu : les compteurs à zéro ne signifient pas l\'absence de discussions sur votre marque. Lancez une collecte manuelle ou attendez le prochain cycle du moteur continu.',
        },
    };
}

// ──────────────────────────────────────────────────────────────
// Main entry — reads from persisted community data
// ──────────────────────────────────────────────────────────────

export async function getSocialSlice(clientId) {
    const { values, dataSources, errors } = await loadIndependentSources({
        client: () => dbGetClientById(clientId),
        connectorRows: () => getClientConnectorRows(clientId),
        stats: () => getCommunityStats(clientId),
        clusters: () => listClusters(clientId),
        opportunities: () => listOpportunities(clientId, { status: null }),
        latestRun: () => getLatestCollectionRun(clientId),
    });
    const { client, stats, latestRun } = values;
    const clusters = values.clusters || [];
    const opportunities = values.opportunities || [];
    const connectorRow = (values.connectorRows || []).find((row) => row.provider === 'agent_reach') || null;
    const availability = { status: getSourceStatus(dataSources), dataSources, errors };
    const connection = resolveConnectionStatus(connectorRow, latestRun, stats, dataSources);

    if (
        availability.status === 'available' &&
        connection.status === 'not_connected' &&
        stats?.documents === 0 &&
        !latestRun
    ) {
        return buildNotConnectedSlice(client, availability);
    }

    const topComplaints = formatClusterItems(clusters, 'complaint');
    const topQuestions = formatClusterItems(clusters, 'question');
    const topThemes = formatClusterItems(clusters, 'theme', { maxItems: 12 });
    const communityLanguage = formatClusterItems(clusters, 'language', { maxItems: 8 });
    const competitorComplaints = formatClusterItems(clusters, 'competitor_complaint', { maxItems: 8 });
    const sourceBuckets = formatSourceBuckets(clusters);

    const faqOpportunities = formatOpportunities(opportunities, 'faq', { maxItems: 6 });
    const contentOpportunities = formatOpportunities(opportunities, 'content', { maxItems: 8 });
    const differentiationAngles = formatOpportunities(opportunities, 'differentiation', { maxItems: 6 });

    // v2 opportunity types
    const buyerQuestions = formatOpportunities(opportunities, 'recurring_buyer_question', { maxItems: 6 });
    const comparisonDiscussions = formatOpportunities(opportunities, 'comparison_discussion', { maxItems: 4 });
    const painPoints = formatOpportunities(opportunities, 'recurring_pain_point', { maxItems: 4 });
    const responseOpportunities = formatOpportunities(opportunities, 'response_opportunity', { maxItems: 4 });
    const aiMentionOpportunities = formatOpportunities(opportunities, 'ai_mention_opportunity', { maxItems: 4 });
    const contentAngleOpportunities = formatOpportunities(opportunities, 'content_opportunity', { maxItems: 4 });

    const isConnected = connection.status === 'connected' || connection.status === 'connected_empty' || connection.status === 'syncing';

    return {
        ...availability,
        provenance: {
            observation: getProvenanceMeta('observed'),
            inferred: getProvenanceMeta('inferred'),
            not_connected: getProvenanceMeta('not_connected'),
        },
        connection,
        summary: {
            generated_at: new Date().toISOString(),
            total_discussions: stats?.documents ?? null,
            unique_sources: values.clusters == null ? null : sourceBuckets.length,
            documents_count: stats?.documents ?? null,
            clusters_count: stats?.clusters ?? null,
            opportunities_count: stats?.opportunities ?? null,
            mentions_count: stats?.mentions ?? null,
            site_context: dataSources.client === 'unavailable' ? null : buildSiteContext(client),
            query_seeds: latestRun?.seed_queries || [],
            last_run: latestRun ? {
                id: latestRun.id,
                status: latestRun.status,
                started_at: latestRun.started_at,
                finished_at: latestRun.finished_at,
                documents_collected: latestRun.documents_collected,
                documents_persisted: latestRun.documents_persisted,
                run_context: latestRun.run_context || null,
            } : null,
        },
        topComplaints,
        topQuestions,
        topThemes,
        sourceBuckets,
        competitorComplaints,
        communityLanguage,
        faqOpportunities,
        contentOpportunities,
        differentiationAngles,
        // v2 opportunity types
        buyerQuestions,
        comparisonDiscussions,
        painPoints,
        responseOpportunities,
        aiMentionOpportunities,
        contentAngleOpportunities,
        emptyState:
            availability.status !== 'available' || stats == null
                ? {
                      title: 'Données communautaires indisponibles',
                      description:
                          'Certaines données communautaires sont temporairement indisponibles. Les données connues sont conservées.',
                  }
                : !isConnected || stats.documents === 0 ? {
            title: latestRun && stats.documents === 0
                ? 'Aucun document pertinent collecté pour le moment'
                : 'Aucune donnée communautaire collectée',
            description: latestRun && stats.documents === 0
                ? `La dernière collecte (${latestRun.status}) n'a pas trouvé de nouveau document pertinent. Les seeds seront enrichis lors des prochaines exécutions, ce qui ne signifie pas l'absence de discussions sur votre marque.`
                : 'Le connecteur est actif mais aucune discussion externe n\'a encore été collectée. La prochaine collecte sera déclenchée par le moteur continu.',
        } : null,
    };
}
